### ISSUE TITLE
I think you are special

### ISSUE THREAD

**Issue by squee666** [gnmmarechal/frankenupdater#1]
EDIT: Not an issue.

ALSO:

I (gnmmarechal) make the app I want to - it's not up to you to tell me what to do.

Have a nice day.

If this serves no purpose to you, it might still serve someone else.

**Comment by astronautlevel2** [comment]
This app is pretty pointless honestly. 

We have kernel exploit on 10.7, so there's no point in frankenfirmware.

Given that this requires you to download the CIAs from the NUS anyway you might as well just use sysupdater which will work *exactly the same.*

Also, perhaps more importantly, there's no point in installing CIAs for frankenfirmware. ctr-httpwn is safer and not permanent, allowing it to be enabled or disabled on the fly.

**Comment by Jackus-RM** [comment]
This app serves no purpose whatsoever, as said above.
If you want to contribute to the 3ds scene, try making an app that actually does something that current apps can't already do.

**Comment by gnmmarechal** [comment]
This is intended to make it more foolproof. I know it can be installed with
FBI/NASA. I wrote a tutorial on that lmao.

But some feel uneasy doing it manually via a CIA Manager. Which is why I
made the script.

**Comment by gnmmarechal** [comment]
Frankenfirms are permanent - I don't know about you, but it's annoying to
have to use CTR-HTTPWN each time I want to go online. Also, HTTPWN doesn't
work on games that force reboot (ex. SSB on o3DS)

**Comment by gnmmarechal** [comment]
Also, this script CHECKS if you are using the correct title for your region
and model before installing. FBI/NASA does not.

**Comment by ihaveamac** [comment]
ctr-httpwn is still safer and preferred instead of trying to do a "franken-firmware" though because you aren't mixing different versions of important titles on NAND. a "franken-firmware" is arguably more dangerous than either using ctr-httpwn or downgrading.

**Comment by gnmmarechal** [comment]
@ihaveamac sure, it is safer, But for those of us who want homebrew, don't have OoT/Cubic Ninja, and are not willing to format their consoles (since many have gotten a softbrick by downgrading without formatting, including myself), this is an option. Also, on o3DS, if you want to stay on 10.3, for example, and play SSB online, you _do_ need a frankenfirmware, as CTR-HTTPWN won't work.

Additionally, a frankenfirmware is simply an option, that can be considered under certain circumstances. 

Are there better options? Sure.
Am I willing to format to use those better options? Nope.
Do I have any other options without formatting? Nope.

And I'm not the only one.
