### ISSUE TITLE
More spam

### ISSUE THREAD

**Issue by L33thaxor112** [gnmmarechal/frankenupdater#3]
Title. 

Plus :
![image](https://cloud.githubusercontent.com/assets/19195440/15029210/3546d7dc-1212-11e6-909b-428f4a6a60cc.jpeg)

We arent going to stop until you delete this repo because its 1. Stupid, 2. Useless when CTRPwn exsists, and 3. Is going to cause a lot of bricks if people aren't careful.

**Comment by astronautlevel2** [comment]
Although I do agree this project is not useful for most things, opening up issues and harassing the developer won't help matters.

EDIT: I also see you created your account today, likely solely for the purpose of harassing the dev without your name being associated with it. If you need to hide in order to prevent negative repercussions you probably shouldn't be doing that thing in the first place.

**Comment by gnmmarechal** [comment]
It _might_ be useful in very _few_ situations, but I want it to work. It's no reason for you lot to keep doing this crap.
